'use client'

import { useCallback, useLayoutEffect, useRef, useState } from 'react'
import { QR_GOLD } from '@/lib/adCreative'
import { cn } from '@/lib/utils'

// The scan-to-act QR exactly as the TV overlays it: a bare, gold-framed code whose
// CENTER sits at (x, y) as fractions of the frame and whose WIDTH is `size` as a
// fraction of the frame width — the same overlay math the TV player uses. Padding,
// corner radius, and the ring all scale with the chip's OWN measured width, so the
// proportions are identical whether it renders in a ~640px editor preview or the
// 1920px TV stage. The gold is a FIXED value (not the `--primary` theme token, which
// is bronze in light mode) so a light-mode editor matches the always-dark TV.
// The QR image `src` (a data URL) is generated by the caller. `interactive` makes
// the chip draggable within its positioned parent, reporting the new center via onMove.
export function QrChip({
  src,
  x,
  y,
  size,
  interactive = false,
  onMove,
  className,
}: {
  src: string | null
  x: number
  y: number
  size: number
  interactive?: boolean
  onMove?: (x: number, y: number) => void
  className?: string
}) {
  const ref = useRef<HTMLDivElement>(null)
  const [w, setW] = useState(0)

  // Measure our own width so padding/radius/ring stay proportional at any scale.
  useLayoutEffect(() => {
    const el = ref.current
    if (!el) return
    const measure = () => setW(el.offsetWidth)
    measure()
    const ro = new ResizeObserver(measure)
    ro.observe(el)
    return () => ro.disconnect()
  }, [])

  // Ratios reproduce the TV look at qr_size 0.09 (172.8px chip: 6px pad, 12px
  // radius, 2px ring). See TvPlayer's `p-1.5 rounded-xl ring-2`.
  const pad = w * 0.035
  const radius = w * 0.069
  const ring = w * 0.012

  const onPointerDown = useCallback(
    (e: React.PointerEvent<HTMLDivElement>) => {
      if (!interactive || !onMove) return
      // Don't let the grab bubble to the editor's drag-to-move handler.
      e.preventDefault()
      e.stopPropagation()
      const chip = ref.current
      const parent = chip?.offsetParent as HTMLElement | null
      if (!chip || !parent) return
      chip.setPointerCapture(e.pointerId)
      const move = (ev: PointerEvent) => {
        const r = parent.getBoundingClientRect()
        if (!r.width || !r.height) return
        const mx = chip.offsetWidth / 2 / r.width
        const my = chip.offsetHeight / 2 / r.height
        // pointer as a fraction of the frame, clamped so the whole chip stays inside
        const nx = Math.min(1 - mx, Math.max(mx, (ev.clientX - r.left) / r.width))
        const ny = Math.min(1 - my, Math.max(my, (ev.clientY - r.top) / r.height))
        onMove(nx, ny)
      }
      const up = () => {
        window.removeEventListener('pointermove', move)
        window.removeEventListener('pointerup', up)
      }
      window.addEventListener('pointermove', move)
      window.addEventListener('pointerup', up)
    },
    [interactive, onMove]
  )

  return (
    <div
      ref={ref}
      onPointerDown={onPointerDown}
      className={cn(
        'absolute touch-none select-none',
        interactive ? 'cursor-grab active:cursor-grabbing' : 'pointer-events-none',
        className
      )}
      style={{
        left: `${x * 100}%`,
        top: `${y * 100}%`,
        width: `${size * 100}%`,
        transform: 'translate(-50%, -50%)',
        background: '#ffffff',
        padding: pad,
        borderRadius: radius,
        boxShadow: `0 0 0 ${ring}px ${QR_GOLD}`,
      }}
    >
      {src ? (
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={src}
          alt="Scan"
          draggable={false}
          className="block w-full"
          style={{ borderRadius: ring }}
        />
      ) : (
        <div className="w-full" style={{ aspectRatio: '1 / 1', borderRadius: ring, background: '#e5e7eb' }} />
      )}
    </div>
  )
}
