#!/bin/sh
# provision-kiosk.sh — turn a freshly-flashed Raspberry Pi OS (Trixie, labwc/Wayland)
# into a Loop Network TV kiosk in one command. Idempotent; safe to re-run.
#
# Run it ON the Pi, as user `loop`, after first boot:
#   ./provision-kiosk.sh LM-XXXXX
#   ./provision-kiosk.sh LM-XXXXX https://loop-network-one.vercel.app   # custom base URL
#
# It writes the kiosk launcher, hides the mouse cursor, and picks the right GPU
# mode for the Pi model. Then reboot (one sudo line, printed at the end).

set -e

CODE="$1"
BASE="${2:-https://loop-network-one.vercel.app}"

if [ -z "$CODE" ]; then
  echo "ERROR: pass the pairing code, e.g.  ./provision-kiosk.sh LM-563BMA" >&2
  exit 1
fi

URL="$BASE/tv?code=$CODE"
LABWC="$HOME/.config/labwc"
mkdir -p "$LABWC"
echo "==> Provisioning kiosk for $CODE"
echo "    URL: $URL"

# --- 1. GPU flags by Pi model -------------------------------------------------
# Pi 3B+ and older: VideoCore IV GPU = OpenGL ES 2.0 only, but the Raspberry Pi
# chromium wrapper forces --use-angle=gles (ES 3.0). The driver rejects it, the
# GPU process crash-loops at ~100% CPU, no frame ever paints, and the TV shows
# the desktop instead of the player. Fix: force software ANGLE (swiftshader).
# Pi 4 / Pi 5 have newer GPUs that do ES 3.0, so let them use hardware GL.
MODEL="$(tr -d '\0' < /proc/device-tree/model 2>/dev/null || echo unknown)"
case "$MODEL" in
  *"Pi 4"*|*"Pi 5"*|*"Pi 400"*|*"Compute Module 4"*|*"Compute Module 5"*)
    GPU_FLAGS=""
    echo "==> $MODEL  ->  hardware GL" ;;
  *)
    GPU_FLAGS="--use-angle=swiftshader --use-gl=angle"
    echo "==> $MODEL  ->  software render (swiftshader)" ;;
esac

# --- 2. Invisible (transparent) mouse cursor ---------------------------------
THEME="$HOME/.local/share/icons/blank"
mkdir -p "$THEME/cursors"
cat > "$THEME/index.theme" <<EOF
[Icon Theme]
Name=blank
Comment=transparent cursor
EOF
python3 - "$THEME/cursors" <<'PY'
import struct, os, sys
cur = sys.argv[1]
size = 24
# a 1x1 fully-transparent Xcursor
img  = struct.pack('<IIIIIIIII', 36, 0xfffd0002, size, 1, 1, 1, 0, 0, 0) + struct.pack('<I', 0)
data = b'Xcur' + struct.pack('<III', 16, 0x10000, 1) + struct.pack('<III', 0xfffd0002, size, 28) + img
open(os.path.join(cur, 'left_ptr'), 'wb').write(data)
for n in ['default','pointer','hand1','hand2','hand','text','xterm','arrow',
          'top_left_arrow','watch','wait','crosshair','ibeam','fleur',
          'question_arrow','sb_h_double_arrow','sb_v_double_arrow','grab','grabbing','left_ptr_watch']:
    p = os.path.join(cur, n)
    if os.path.lexists(p):
        os.remove(p)
    os.symlink('left_ptr', p)
print("    blank cursor theme: %d entries" % len(os.listdir(cur)))
PY

# --- 3. labwc environment (keyboard + blank cursor) --------------------------
# User file wins over the system default (/etc/xdg/labwc/environment = PiXtrix).
cat > "$LABWC/environment" <<EOF
XKB_DEFAULT_MODEL=pc105
XKB_DEFAULT_LAYOUT=us
XKB_DEFAULT_VARIANT=
XKB_DEFAULT_OPTIONS=
XCURSOR_THEME=blank
XCURSOR_SIZE=24
EOF

# --- 4. labwc autostart (the kiosk launcher) ---------------------------------
[ -f "$LABWC/autostart" ] && cp "$LABWC/autostart" "$LABWC/autostart.bak.$(date +%s)"
cat > "$LABWC/autostart" <<EOF
#!/bin/sh
# Loop Network TV kiosk — generated by provision-kiosk.sh. HDMI-only, self-healing.
URL="$URL"
PROFILE="\$HOME/.config/chromium"

# Turn the small DSI panel off; HDMI is the venue screen.
wlr-randr --output DSI-1 --off 2>/dev/null

# Cold-boot race fix: wait for the HDMI output before launching Chromium, or the
# window never maps and the TV shows the desktop.
i=0
while [ \$i -lt 30 ]; do
  wlr-randr 2>/dev/null | grep -q '^HDMI-A-1' && break
  i=\$((i + 1)); sleep 1
done

# Relaunch forever if Chromium exits; clear any stale singleton lock first.
(
  while true; do
    rm -f "\$PROFILE"/Singleton* 2>/dev/null
    /usr/bin/chromium "\$URL" \\
      --kiosk --start-fullscreen \\
      --ozone-platform=wayland --password-store=basic \\
      $GPU_FLAGS \\
      --noerrdialogs --disable-infobars --no-first-run \\
      --disable-session-crashed-bubble --disable-restore-session-state \\
      --check-for-update-interval=604800
    sleep 3
  done
) &
EOF
chmod +x "$LABWC/autostart"
echo "    wrote $LABWC/autostart  +  environment"

# --- 5. Disable screen blanking (needs sudo) ---------------------------------
if sudo -n raspi-config nonint do_blanking 1 2>/dev/null; then
  echo "    screen blanking disabled"
  BLANK_DONE=1
else
  BLANK_DONE=0
fi

echo
echo "==> KIOSK CONFIGURED."
if [ "$BLANK_DONE" = "0" ]; then
  echo "    Two lines still need your password (run with the ! prefix):"
  echo "      sudo raspi-config nonint do_blanking 1   # stop the screen sleeping"
  echo "      sudo reboot                              # launch the kiosk"
else
  echo "    Reboot to launch the kiosk:   sudo reboot"
fi
