-- Loop Network — broaden the venue/advertiser category catalog.
--
-- 0016 covered food/fitness/personal-care/auto/retail basics (47 total), but the
-- signup + buy-flow pickers were missing whole verticals that advertise on local
-- TV: home services, professional services, most health/wellness, entertainment,
-- childcare, and a deeper retail/food list. This adds them. Idempotent: guarded
-- on the unique slug, so re-running (or overlap with 0016) is a no-op.

insert into categories (name, slug) values
  -- Food & drink (deeper)
  ('Steakhouse',                 'steakhouse'),
  ('Sushi / Japanese',           'sushi'),
  ('Mexican Restaurant',         'mexican'),
  ('Italian Restaurant',         'italian'),
  ('BBQ / Smokehouse',           'bbq'),
  ('Seafood Restaurant',         'seafood'),
  ('Diner',                      'diner'),
  ('Deli / Sandwich Shop',       'deli'),
  ('Ice Cream / Dessert',        'ice_cream'),
  ('Donut Shop',                 'donut'),
  ('Juice / Smoothie Bar',       'juice_bar'),
  ('Food Truck',                 'food_truck'),
  ('Sports Bar',                 'sports_bar'),
  ('Catering',                   'catering'),
  -- Home services
  ('HVAC / Heating & Cooling',   'hvac'),
  ('Plumbing',                   'plumbing'),
  ('Electrician',                'electrician'),
  ('Roofing',                    'roofing'),
  ('Landscaping / Lawn Care',    'landscaping'),
  ('Pest Control',               'pest_control'),
  ('Cleaning Service',           'cleaning'),
  ('Painting / Painter',         'painting'),
  ('General Contractor',         'contractor'),
  ('Home Remodeling',            'remodeling'),
  ('Flooring',                   'flooring'),
  ('Garage Doors',               'garage_door'),
  ('Pool Service',               'pool_service'),
  ('Moving Company',             'moving'),
  ('Handyman',                   'handyman'),
  ('Window / Glass',             'window_glass'),
  ('Fencing / Decks',            'fencing'),
  ('Solar',                      'solar'),
  ('Septic / Well',              'septic'),
  -- Professional services
  ('Insurance Agency',           'insurance'),
  ('Law Firm / Attorney',        'attorney'),
  ('Accounting / Tax',           'accounting'),
  ('Financial Advisor',          'financial_advisor'),
  ('Mortgage / Lender',          'mortgage'),
  ('Marketing / Advertising',    'marketing'),
  ('Photography',                'photography'),
  ('Printing / Signs',           'printing'),
  ('IT / Computer Repair',       'it_services'),
  ('Staffing / Recruiting',      'staffing'),
  ('Travel Agency',              'travel'),
  -- Health & wellness
  ('Physical Therapy',           'physical_therapy'),
  ('Optometry / Eye Care',       'optometry'),
  ('Dermatology',                'dermatology'),
  ('Orthodontist',               'orthodontist'),
  ('Mental Health / Therapy',    'mental_health'),
  ('Pediatrics',                 'pediatrics'),
  ('Women''s Health / OB-GYN',   'obgyn'),
  ('Weight Loss Clinic',         'weight_loss'),
  ('IV Therapy / Wellness',      'iv_therapy'),
  ('Hearing / Audiology',        'hearing'),
  ('Nutrition / Dietitian',      'nutrition'),
  ('Cosmetic Surgery',           'cosmetic_surgery'),
  ('Acupuncture',                'acupuncture'),
  -- Personal care & beauty (deeper)
  ('Eyelash / Brow Bar',         'lash_brow'),
  ('Waxing Studio',              'waxing'),
  ('Permanent Makeup',           'permanent_makeup'),
  ('Blow Dry Bar',               'blow_dry'),
  ('Skincare / Esthetician',     'skincare'),
  -- Fitness & recreation (deeper)
  ('CrossFit Box',               'crossfit'),
  ('Cycling / Spin Studio',      'cycling'),
  ('Boxing / Kickboxing',        'boxing'),
  ('Personal Training',          'personal_training'),
  ('Pilates Studio',             'pilates'),
  ('Climbing Gym',               'climbing'),
  ('Gymnastics',                 'gymnastics'),
  ('Swim School',                'swim'),
  -- Automotive (deeper)
  ('Auto Body / Collision',      'auto_body'),
  ('Window Tinting',             'window_tint'),
  ('Auto Detailing',             'auto_detail'),
  ('Towing',                     'towing'),
  ('Auto Parts',                 'auto_parts'),
  ('Motorcycle / Powersports',   'powersports'),
  -- Retail (deeper)
  ('Jewelry Store',              'jewelry'),
  ('Furniture Store',            'furniture'),
  ('Florist',                    'florist'),
  ('Cell Phone / Electronics',   'electronics'),
  ('Clothing Boutique',          'clothing'),
  ('Thrift / Consignment',       'thrift'),
  ('Sporting Goods',             'sporting_goods'),
  ('Hardware Store',             'hardware'),
  ('Gift Shop',                  'gift_shop'),
  ('Bookstore',                  'bookstore'),
  ('Mattress Store',             'mattress'),
  ('Bike Shop',                  'bike_shop'),
  ('Vape Shop',                  'vape'),
  ('CBD Store',                  'cbd'),
  ('Toy Store',                  'toy_store'),
  ('Garden Center / Nursery',    'garden_center'),
  -- Entertainment & events
  ('Movie Theater',              'movie_theater'),
  ('Trampoline Park',            'trampoline'),
  ('Escape Room',                'escape_room'),
  ('Mini Golf',                  'mini_golf'),
  ('Axe Throwing',               'axe_throwing'),
  ('Skating Rink',               'skating'),
  ('Go-Karts',                   'go_karts'),
  ('Event Venue / Banquet Hall', 'event_venue'),
  ('Casino',                     'casino'),
  ('Museum / Attraction',        'attraction'),
  -- Education & childcare
  ('Daycare / Preschool',        'daycare'),
  ('Tutoring / Learning Center', 'tutoring'),
  ('Driving School',             'driving_school'),
  ('Music Lessons',              'music_lessons'),
  ('Cheer Gym',                  'cheer'),
  -- Pet (deeper)
  ('Dog Boarding / Daycare',     'dog_boarding'),
  ('Pet Grooming',               'pet_grooming'),
  ('Pet Training',               'pet_training'),
  -- Other / community
  ('Storage Facility',           'storage'),
  ('Apartments / Property Mgmt', 'property_management'),
  ('Senior Living',              'senior_living'),
  ('Funeral Home',               'funeral'),
  ('Church / Place of Worship',  'church'),
  ('Nonprofit / Charity',        'nonprofit')
on conflict (slug) do nothing;
